# Site settings
title: Yufan Deng Blog
SEOTitle: 邓钰凡的博客 | Yufan Deng Blog
header-img: img/FC27A3DA-B15F-4151-90EB-943F8537D667.jpeg
email: dengyufan666666@gmail.com
description: "这里是 @Yufan Deng 邓钰凡 的个人博客，与你一起发现更大的世界 | 要做一个财富自由的混吃大学牲"
keyword: "邓钰凡, Yufan Deng 邓钰凡, Yufan Deng, 鬼栈, Yufan Deng, @Yufan Deng, Yufan Deng的博客, Yufan Deng, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"
url: "https://13066191457.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: 邓钰凡200110
zhihu_username: dengyufan
github_username: 13066191457
twitter_username: 286846966
#facebook_username:  dengyufan666666@gmai.com
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2023, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 11
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: dengyufan

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: 13066191457.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "要做一个划水大学牲 <br> React Team @ Meta"
sidebar-avatar: https://cdn.jsdelivr.net/gh/13066191457/dyf@main/202302201652848.JPG # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
# 学习
    { title: "广医主页", href: "https://www.gzhmu.edu.cn" },
    { title: "广医校园网", href: "http://192.168.12.3" },
    
    { title: "广医学习资料(谷歌)", href: "https://drive.google.com/drive/folders/1F_5rvM47FghHvkULkI2VemC-QmI_R2Zx?usp=share_link" },
    { title: "广医学习资料(微软)", href: "https://2021163004-my.sharepoint.com/:f:/g/personal/fan_2021163004_onmicrosoft_com/Eh-VAxsF9g9Ek9FnZ8CLv-oB9vfRV9n_tfgapez7DwsGmA?e=K6eS0k" },
    { title: "南方医主页", href: "https://www.smu.edu.cn" },
    { title: "南医学习资料", href: "https://2021163004-my.sharepoint.com/:f:/g/personal/fan_2021163004_onmicrosoft_com/EsY3U0_jhT1Ni0N24UISfxcB4P4eKzwaxe7JoqPBcq76Sw?e=NYT5L1" },
# 影视娱乐
    { title: "IP查询", href: "https://ping.pe" },
    
    { title: "批改网", href: "https://www.pigai.org" },
    { title: "YouTube", href: "https://www.youtube.com" },
   
    { title: "动漫观看地址1", href: "https://www.dm530p.net" },
    { title: "动漫观看地址2", href: "https://www.agemys.net" },
    { title: "奈飞", href: "https://www.netflix.com" },
    { title: "奈飞账号（购买不易，请手下留情）", href: "https://www.dengyufan.icu/关于/" },
    { title: "AI绘画", href: "https://playgroundai.com" },
    { title: "AI照片卡通化", href: "https://toonme.com" },
    { title: "Adobe fire", href: "https://firefly.adobe.com" },
    { title: "照片动态", href: "https://convert.leiapix.com" },
    { title: "自动生成ppt", href: "https://www.prezo.ai/" },
    { title: "PPT", href: "https://chat-ppt.com" },
    { title: "PDF", href: "https://www.chatpdf.com " },
    { title: "DOC", href: "https://chatdoc.com " },
    { title: "文件信息总结", href: "https://www.humata.ai" },
    { title: "Notion", href: "https://www.notion.so/product/ai " },
    { title: "论文", href: "https://www.paperbrain.study" },
    
    { title: "虚拟手机卡", href: "https://yunjiema.net" },
    { title: "WiKi", href: "https://www.wikipedia.org" },
    { title: "OpenAI", href: "https://chat.openai.com/chat" },
    { title: "万方", href: "https://www.wanfangdata.com.cn/index.html" },
    { title: "中国知网", href: "https://www.cnki.net" },
    { title: "阿里云", href: "https://www.aliyun.com/product/oss" },
    { title: "电视剧1", href: "https://guazitv.tv" },
    { title: "电视剧2", href: "https://www.duboku.tv" },
    { title: "电影1", href: "https://www.pdoro.com" },
    { title: "电影2", href: "https://www.yinfans.me/" },
    { title: "变声器1", href: "https://www.voicemod.net" },
    { title: "变声器2", href: "https://tw.imyfone.com" },
    { title: "变声器3", href: "https://clownfish-translator.com/voicechanger/download.html" },
    { title: "Windows ", href: "" },
    { title: "Android ", href: "" },
    { title: "Mac OS ", href: "https://qingyun.filebases.com/assets/Clash.for.Windows-0.20.16.dmg" },
    { title: "iOS", href: "https://apps.apple.com/us/app/shadowrocket/id932747118" },
    { title: "C9高校网盘", href: "https://www.seafile.com/home" },
    { title: "广医云盘", href: "http://i.mooc.chaoxing.com/space" },
    { title: "网盘密码666666", href: "http://dyf.icu/bd/" },
    
    { title: "Mircosoft会员账号（两年有效期）", href: "https://cdn.jsdelivr.net/gh/13066191457/dyf@main/202307182158784.docx" },
    
    { title: "网站盲盒（划水好东西）", href: "https://sharkle.com" },
    { title: "名字模拟器", href: "www.qmsjmfb.com" },

    { title: "chatgpt自建,密码666666", href: "https://aaa.dyf.world" },
    { title: "chatgpt自建,密码ABC666666...", href: "https://gz.dyf.icu" },
    
    { title: "New bing", href: "https://www.bing.com/" },
    { title: "AI集合", href: "https://docs.google.com/document/d/e/2PACX-1vSIP9dJDGt3NdGXm84IdagMFKnO3GoMEtJz0yXD-GTX0D9FXXMCDXHRLzaMZwCMD5x_O9oUgq060uHL/pub"},
  { title: "AI集合2", href: "https://kdocs.cn/l/cqMaRYW4PsST" },  
  { title: "bard", href: "https://bard.google.com" }
  ]
