# Site settings
title: Yufan Deng Blog
SEOTitle: 邓钰凡的博客 | Yufan Deng Blog
header-img: img/FC27A3DA-B15F-4151-90EB-943F8537D667.jpeg
email: dengyufan666666@gmail.com
description: "这里是 @Yufan Deng 邓钰凡 的个人博客，与你一起发现更大的世界 | 要做一个财富自由的混吃大学牲"
keyword: "邓钰凡, Yufan Deng 邓钰凡, Yufan Deng, 鬼栈, Yufan Deng, @Yufan Deng, Yufan Deng的博客, Yufan Deng, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"
url: "https://13066191457.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: 邓钰凡200110
zhihu_username: dengyufan
github_username: 13066191457
twitter_username: 286846966
#facebook_username:  dengyufan666666@gmai.com
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2023, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 11
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: dengyufan

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: 13066191457.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "要做一个划水大学牲 <br> React Team @ Meta"
sidebar-avatar: https://cdn.jsdelivr.net/gh/13066191457/dyf@main/202302201652848.JPG # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "广医主页", href: "https://www.gzhmu.edu.cn" },
    { title: "广医校园网", href: "http://192.168.12.3" },
    
    { title: "广医学习资料（完善中）", href: "https://gzhum-my.sharepoint.com/:f:/g/personal/286846966_gzhum_onmicrosoft_com/EvhCQVuqxaFDrOFHfvqy3bUBpAdgoi5BqRfM_ej8Tr3V9A?e=Atg6pL" },
    { title: "南方医主页", href: "www.smu.edu.cn" },
    { title: "IP查询", href: "https://ping.pe" },
    
    { title: "批改网", href: "https://www.pigai.org" },
    { title: "YouTube", href: "https://www.youtube.com" },
    { title: "VPN后台(已建好)谷歌浏览器访问，Safari不老实doge", href: "https://www.dyf.icu:55555" },
    { title: "VPN后台(账号密码默认admin）", href: "https://www.dyf.icu:55555" },
    { title: "动漫观看地址1", href: "https://www.dm530p.net" },
    { title: "动漫观看地址2", href: "https://www.agemys.net" },
    { title: "奈飞", href: "https://www.netflix.com" },
    { title: "奈飞账号（购买不易，请手下留情）", href: "https://https://www.dengyufan.icu/blob/master/奈飞.md" },
    { title: "AI绘画", href: "https://dreamlike.art" },
    { title: "AI照片卡通化", href: "https://toonme.com" },
    { title: "虚拟手机卡", href: "https://quackr.io" },
    { title: "WiKi", href: "https://www.wikipedia.org" },
    { title: "OpenAI", href: "https://chat.openai.com/chat" },
    { title: "万方", href: "https://www.wanfangdata.com.cn/index.html" },
    { title: "中国知网", href: "https://www.cnki.net" },
    { title: "阿里云", href: "https://www.aliyun.com/product/oss" },
    { title: "电视剧1", href: "https://guazitv.tv" },
    { title: "电视剧2", href: "https://www.duboku.tv" },
    { title: "电影1", href: "https://www.pdoro.com" },
    { title: "电影2", href: "https://www.yinfans.me/" },
    { title: "Windows VPN下载", href: "https://qingyun.filebases.com/assets/Clash.for.Windows-0.20.16-win.7z" },
    { title: "Android VPN下载", href: "https://qingyun.filebases.com/assets/cfa-2.5.12-foss-arm64-v8a-release.apk" },
    { title: "Mac OS VPN下载", href: "https://qingyun.filebases.com/assets/Clash.for.Windows-0.20.16.dmg" },
    { title: "iOS VPN下载", href: "https://apps.apple.com/us/app/shadowrocket/id932747118" },
    { title: "C9高校网盘", href: "https://www.seafile.com/home" },
    { title: "广医网盘", href: "http://i.mooc.chaoxing.com/space" },
    { title: "Mircosoft会员账号（两年有效期）", href: "https://dengyufan.oss-cn-hongkong.aliyuncs.com/test202302271945285.docx" },
    { title: "南医学习资料（可编辑）", href: "https://gzhum-my.sharepoint.com/:f:/g/personal/286846966_gzhum_onmicrosoft_com/EnHBtRXDWzxPvIewe3ZLuzABsVD4hNReR4wVM14sI4NjJw?e=WfD0rY" },
    { title: "网站盲盒（划水好东西）", href: "https://sharkle.com" },
    { title: "名字模拟器", href: "www.qmsjmfb.com" },

    
  ]
