# Site settings
title: Yufan Deng Blog
SEOTitle: 邓钰凡的博客 | Yufan Deng Blog
header-img: img/home-bg.jpg
email: dengyufan666666@gmail.com
description: "这里是 @Yufan Deng 邓钰凡 的个人博客，与你一起发现更大的世界 | 要做一个财富自由的混吃大学牲"
keyword: "邓钰凡, Yufan Deng 邓钰凡, Yufan Deng, 鬼栈, Yufan Deng, @Yufan Deng, Yufan Deng的博客, Yufan Deng, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"
url: "https://13066191457.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: 邓钰凡200110
zhihu_username: dengyufan
github_username: 13066191457
twitter_username: 286846966
#facebook_username:  dengyufan666666@gmai.com
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2023, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: dengyufan

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: 13066191457.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "要做一个划水大学牲 <br> React Team @ Meta"
sidebar-avatar: https://cdn.jsdelivr.net/gh/13066191457/dyf@main/202302201652848.JPG # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "广医主页", href: "https://www.gzhmu.edu.cn" },
    { title: "广医校园网", href: "http://192.168.12.3" },
    { title: "IP查询", href: "https://ping.pe" },
    { title: "批改网", href: "https://www.pigai.org" },
    { title: "YouTube", href: "https://www.youtube.com" },
    { title: "VPN", href: "http://54.176.81.246:54321" },
    { title: "动漫观看地址1", href: "http://ktkkt.top" },
    { title: "动漫观看地址2", href: "https://www.mandao.tv" },
    { title: "奈飞", href: "https://www.netflix.com" },
    { title: "AI绘画", href: "https://lexica.art" },
    { title: "虚拟手机卡", href: "https://quackr.io" },
    { title: "WiKi", href: "https://www.wikipedia.org" },
    { title: "OpenAI", href: "https://chat.openai.com/chat" },
    { title: "万方", href: "https://www.wanfangdata.com.cn/index.html" },
    { title: "中国知网", href: "https://www.cnki.net" },
    { title: "阿里云", href: "https://www.aliyun.com/product/oss" },
    { title: "电视剧1", href: "https://guazitv.tv" },
    { title: "电视剧2", href: "https://www.duboku.tv" },
    { title: "Windows VPN下载", href: "https://qingyun.filebases.com/assets/Clash.for.Windows-0.20.16-win.7z" },
    { title: "Android VPN下载", href: "https://qingyun.filebases.com/assets/cfa-2.5.12-foss-arm64-v8a-release.apk" },
    { title: "Mac OS VPN下载", href: "https://qingyun.filebases.com/assets/Clash.for.Windows-0.20.16.dmg" },
  ]
